- name: Crear carpeta del servicio {{ service_name }}
  file:
    path: "{{ nebula_base_path }}/{{ service_name }}"
    state: directory
    recurse: true
    owner: "{{ service_owner_uid | default('1000') }}"
    group: "{{ service_owner_uid | default('1000') }}"
  become: true

- name: Generar docker-compose.yml de {{ service_name }}
  template:
    src: "{{ playbook_dir }}/services/{{ service_name }}/docker-compose.yml.j2"
    dest: "{{ nebula_base_path }}/{{ service_name }}/docker-compose.yml"
  become: true

- name: Levantar el servicio {{ service_name }}
  community.docker.docker_compose_v2:
    project_src: "{{ nebula_base_path }}/{{ service_name }}"
    state: present
  become: true