active_domain: nebulacorvi.com
nebula_base_path: /srv/nube
data_path: /srv/nube-data
admin_email: admin@nebulacorvi.com
server_username: scholaris
service_uids:
  prometheus: '65534'
  grafana: '472'
  loki: '10001'
  postgres: '999'
  pgadmin: '5050'
  default: '1000'

todos_los_servicios:
  - traefik
  - portainer
  - homepage
  - minio
  - nextcloud
  - gitea
  - librechat
  - vaultwarden
  - uptime-kuma
  - n8n
  - postgres
  - pgadmin
  - mongodb
  - mongo-express
  - redis
  - redisinsight
  - kopia
  - jupyter
  - umami
  - excalidraw
  - vscode
  - node-exporter
  - cadvisor
  - prometheus
  - grafana
  - loki
  - promtail
  - ttyd
  - technitium

servicios_compose: "{{ todos_los_servicios }}"