active_domain: localhost
nebula_base_path: /srv/nube
data_path: /srv/nube-data
admin_email: admin@nebulacorvi.com
todos_los_servicios:
  - traefik
  - portainer
  - homepage
  - minio
  - nextcloud
  - gitea
  - librechat
  - vaultwarden
  - netdata
  - uptime-kuma
  - n8n
  - postgres
  - pgadmin
  - mongodb
  - mongo-express
  - redis
  - redisinsight
  - kopia
  - jupyter
  - umami
  - penpot
  - vscode
  - collabora

servicios_compose: "{{ todos_los_servicios }}"