# clave cifrada original: CambiaEstaClave123!
panel_auth_htpasswd: "admin:$2y$05$sqyufSNDXTC.tMjmJ/6FC.nWkhXOM5flrM5S3XP.xRkHgAghod18u"
minio_root_user: "admin"
minio_root_password: "CambiaEstaClave123!"
nextcloud_db_root_password: "CambiaEstaClave123!"
nextcloud_db_password: "CambiaEstaClave123!"
gitea_db_password: "CambiaEstaClave123!"
jupyter_token: "CambiaEsteToken123!"
postgres_admin_password: "CambiaEstaClave123!" 
pgadmin_password: "CambiaEstaClave123!"
mongodb_root_password: "CambiaEstaClave123!"
mongo_express_user: "CambiaEstaClave123!"
mongo_express_password: "CambiaEstaClave123!"
redis_password: "CambiaEstaClave123!"
kopia_repo_password: "a3f9c81b2e4d7f0691c3a8b5"
kopia_ui_user: "admin"
kopia_ui_password: "a3f9c81b2e4d7f0691c3a8b5"
grafana_admin_password: "CambiaEstaClave123!"
vscode_password: "CambiaEstaClave123!"
ttyd_user: "admin"
ttyd_password: "CambiaEstaClave123!"
registry_user: "admin"
registry_password: "CambiaEstaClave123!"
rabbitmq_user: "admin"
rabbitmq_password: "CambiaEstaClave123!"
umami_db_password: "CambiaEstaClave123!"
umami_app_secret: "CambiaEstaClave123!"
