minio_root_password: "CambiaEstaClave123!"
nextcloud_db_root_password: "CambiaEstaClave123!"
nextcloud_db_password: "CambiaEstaClave123!"
gitea_db_password: "CambiaEstaClave123!"
jupyter_token: "CambiaEsteToken123!"

postgres_admin_password: "CambiaEstaClave123!" 
pgadmin_password: "CambiaEstaClave123!"
mongodb_root_password: "CambiaEstaClave123!"
mongo_express_user: "CambiaEstaClave123!"
mongo_express_password: "CambiaEstaClave123!"
redis_password: "CambiaEstaClave123!"
restic_access_key: "TU_MINIO_ACCESS_KEY"
restic_secret_key: "TU_MINIO_SECRET_KEY"
restic_repo_url: "s3:http://minio.nebula.local:9002/backups"
